### ISSUE TITLE
Select Text in the Chat

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#10]
would it be possible to select the text in the chat?

**Comment by lluachaturbate** [comment]
The chat is not 1 single piece of formatted text like the CB site.
One of the most important features i wanted to have is to have a different point of view of the chat for every user so you can actually see / test how different users would experience in the same room.
Therefore i made every message a single element, which unfortunately means you can't just select parts of the chat.
I could however make each single message selectable or a function to copy all of it at once if that suits your needs?

**Comment by ghost** [comment]
i just need a way to recover some json  i dump in chat to analize it.

**Comment by lluachaturbate** [comment]
I'll do a simple copy message contextmenu for it then, that should be sufficient.
