### ISSUE TITLE
App sometimes crash when using the keyboard combination CTRL +C

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#12]

**Comment by lluachaturbate** [comment]
Do you mean the JS app or the whole application?
Which OS are you using?
If it's windows, did you compile it yourself or used the binary?
Can you reproduce the error somehow?
Be as thorough as you can, like what control is in focus when you create a crash, what's the text you try to copy etc.

**Comment by ghost** [comment]
OS: Windows 10 Latest Version.

The whole app ransomblly crashes when not in focus and you execute the copy command, but some time happened relativelly randomlly

**Comment by lluachaturbate** [comment]
Ok, i'll set up a windows 10 VM to investigate.
This might take me a few days.
In the meantime if you notice a way to reproduce the error instead of having it randomly appear let me know.

**Comment by ghost** [comment]
Alright how to repro.
1. Open the ADK
2. Load an App 
3. Switch to another window and use any Copy Command, (either CTRL+C or Right Click Copy)

**Comment by ghost** [comment]
ok just had it crash now trying to take a screenshot so i suppose is a clipboard interaction problem, it happens when another app wants to use the clipboard, does the app locks the clipboard?

**Comment by lluachaturbate** [comment]
I'm having trouble setting up a windows 10 VM (VirtualBox and OpenGL in Win10 is buggy) atm.
Do me a favor and try the file i attached. I did small changes in the hope of a _blind_ fix and used a newer Qt version to compile in case of a Qt bug.
[CBADK.zip](https://github.com/lluachaturbate/CBADK/files/364369/CBADK.zip)

**Comment by ghost** [comment]
At the moment I'm not home I will as soon I'm home

Il 14 lug 2016 7:02 PM, "lluachaturbate" notifications@github.com ha
scritto:

**Comment by lluachaturbate** [comment]
Thanks, let me know if the problem persists or not.

**Comment by ghost** [comment]
ok it seems to be gone but 'ill do some more testing

**Comment by lluachaturbate** [comment]
Good to hear, let me know when you feel comfortable it is fixed so i can put it up as a new version.

**Comment by ghost** [comment]
Ok the problem is back , gonna do somemore testing

**Comment by lluachaturbate** [comment]
Weird :/
It's really just those 2 lines i use in the copy message function:

```
QClipboard *cb = QApplication::clipboard();
cb->setText(string);
```

Not like i could do anything wrong there ^^
I think if theres a bug with Qts latest version and windows 10 more people would notice. Maybe some other program you are running interferes with the clipboard?

**Comment by ghost** [comment]
maybe that locks the clipboard? i guess we can try to remove all that copy stuff and go without, and see if it works. any way of dispose that cb instance?

**Comment by ghost** [comment]
anyways im downloading QT myswlf and see if i can try to fix it

**Comment by lluachaturbate** [comment]
It shouldn't lock at all.
I will just use the windows API directly so there can't be any weird stuff happening.
I guess i should be able to do that tomorrow.

**Comment by ghost** [comment]
can u send me a copy of the app compiled without those line at all ? so i can test if that is the cause of the problem

**Comment by ghost** [comment]
after a bit of googling i found out is a common bug, QT still processes the Clipboard evenif the app is not in focus or the one having to handle that specific interaction with the clipboard.

http://stackoverflow.com/questions/31161003/why-does-a-qt-program-process-clipboard-data-when-i-paste-from-clipboard-to-an-e

**Comment by lluachaturbate** [comment]
yes, give me a few minutes.

**Comment by lluachaturbate** [comment]
Ok, so there is a problem with Qts clipboard implementation on windows when there is too much data copied. That's bad.
As i said i'll make a new implementation which uses the windows API then instead.
Shouldn't be a complicated API, the clipboard is pretty simple after all. At least i hope it will be easy :)

**Comment by ghost** [comment]
well it was crashing on me when i was copying blank lines tho,

**Comment by lluachaturbate** [comment]
When you find the time could you give 
[CBADK.zip](https://github.com/lluachaturbate/CBADK/files/367095/CBADK.zip)
a shot?
See if the crashes are gone as well as the "copy message" function of the chat contextmenu still works.

**Comment by ghost** [comment]
ok the problem is still here, i guess we can remove that feature if we can have the content of cb log like in a text log
so that u dont have to use the copy commands

**Comment by lluachaturbate** [comment]
There allready is a CB log widget in the views, so yeah it shouldn't be needed to copy messages.
But that the last version didn't work makes me actually doubt it's the clipboard after all.
Here is a version without the clipboard stuff, please let me know if it crashes as well.
[CBADK.zip](https://github.com/lluachaturbate/CBADK/files/367392/CBADK.zip)

**Comment by ghost** [comment]
Cant test at the moment will do as i get home

Il 16 lug 2016 7:00 PM, "lluachaturbate" notifications@github.com ha
scritto:

**Comment by ghost** [comment]
OK im setting up for a Linux machien so i can get my QT stuff setted up decentlly, and eventually develop there since i have all the tools to do it cross platform

**Comment by lluachaturbate** [comment]
That sounds like the bug still persists?

**Comment by ghost** [comment]
yup. this is the point where normally id write everything from thegroundup  XD

**Comment by ghost** [comment]
im installing QT as we speak

**Comment by ghost** [comment]
ok compiled a version from the current one on githb and the problem is not there so must be a windows andQT specific bug. i guess i  will just deva bit on Linux :) maybe try fix some stuff myself :)

**Comment by lluachaturbate** [comment]
Well that much i knew ^^
I just don't have a windows machine to test and debug.
I committed the other stuff for now, but this bug will have to wait till i find a windows machine to lend.

**Comment by ghost** [comment]
Tried to use the ADK again after a fresh install of Windows. the problems seems to be gone for now!

**Comment by lluachaturbate** [comment]
Well i had no luck recreating that bug as well, just left it open in case somebody else had the same.
It had to be something else interfering i guess.
