### ISSUE TITLE
App option Panel not correctly sized

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#13]
this happens since the last update

![image](https://cloud.githubusercontent.com/assets/7861426/16823005/01119282-4961-11e6-8973-ac24ac06ee69.png)

**Comment by lluachaturbate** [comment]
Yeah i wanted to prevent it from creating a window bigger than the screen.
But doing math in the middle of the night appears to not be a good idea xD.
Will be fixed next version.

**Comment by ghost** [comment]
No Problem :)
