### ISSUE TITLE
Change the cam image to a generic image

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#2]
while its a nice picture i would like to change the cam image (broadcaster imge) to something generic, the good thing about this app is that i can develop apps without being on the actual site and, something more low profile would be appreciated :)

**Comment by lluachaturbate** [comment]
I really didn't think of the rare circumstance that you might not want somebody to see the image.
I'll push an update in a bit to optionally change the cam image. Instructions will be:

Open the CBADK.ini (located next to the binary after you ran it once) and under the "GUI" section add:
`Camimage=/path/to/image.jpg`
Urls will be supported as well.

**Comment by ghost** [comment]
Thanks for the fast response!
