### ISSUE TITLE
Have some Default Users

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#3]
well as the title says having some default users, maybe one for each "kind" would be really usefull

**Comment by lluachaturbate** [comment]
coming up in next release, later today or tomorrow.
Don't know yet how i'll do it, probably an option to make current viewers persistens.

**Comment by ghost** [comment]
how about a json file to load a set user list? you could have a default one (only containing the broadcaster for starter) then as u add user u can persist them on the same file

**Comment by lluachaturbate** [comment]
Sounds good.
I'll pbly not have a default one to keep it 100% portable as just the binary, but you'll be able to create a json file of persistent users.

**Comment by ghost** [comment]
how about something like this?

``` json
{
  "broadcaster": {
    "user": "llua",
    "in_fanclub": false,
    "has_tokens": true,
    "is_mod": false,
    "tipped_recently": false,
    "tipped_alot_recently": false,
    "tipped_tons_recently": false,
    "gender": "m"
  },
  "users": [
    {
      "user": "user2",
      "in_fanclub": false,
      "has_tokens": true,
      "is_mod": false,
      "tipped_recently": false,
      "tipped_alot_recently": false,
      "tipped_tons_recently": false,
      "gender": "m"
    },
    {
      "user": "user2",
      "in_fanclub": false,
      "has_tokens": true,
      "is_mod": false,
      "tipped_recently": false,
      "tipped_alot_recently": false,
      "tipped_tons_recently": false,
      "gender": "m"
    }
  ]
}
```
