### ISSUE TITLE
Restart Debugging on File Changed

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#5]
Would it be possible to propt for a script reload if the file gets changed?

**Comment by lluachaturbate** [comment]
You mean when you change your script file, the app should automatically get restarted?
Sure i can make an option for that. I don't know if I'll have the time today, if not tomorrow.

**Comment by ghost** [comment]
More like "hey the script changed want to restart the app?" Kinda thing
Il 04 apr 2016 8:01 AM, "lluachaturbate" notifications@github.com ha
scritto:

**Comment by lluachaturbate** [comment]
Thinking about it:
If I'd make a automatic reload it would disturb people when they save without a working state.
If you would get prompted upon saving the file, it would be annoying as well.
I think the best way is when i just make a shortcut to reload the app.
Like Ctrl+R reloads the last loaded file.

**Comment by ghost** [comment]
That sounds good
Il 04 apr 2016 10:56 AM, "lluachaturbate" notifications@github.com ha
scritto:
