### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#8]
it would be nice to have an App icon :)

**Comment by lluachaturbate** [comment]
Well I'm terrible with graphical stuff. The best i can do is paint a sticky figure.
But if you or somebody else comes up with an icon i can include it.

**Comment by ghost** [comment]
i can make something. What format you need?

**Comment by lluachaturbate** [comment]
The usual .ico windows icons. I can work with anything tho.

**Comment by lluachaturbate** [comment]
How is the icon coming? Would like to roll it out with the rest of the changes you suggested.

**Comment by ghost** [comment]
[image: Immagine incorporata 1]
atm i have this made it really quick, (ik is horrible but a starting point)

MasterChief36
https://chaturbate.com/masterchief36/

2016-06-26 20:22 GMT+02:00 lluachaturbate notifications@github.com:

**Comment by lluachaturbate** [comment]
Could you link the image please?

**Comment by ghost** [comment]
didnt check if it was here my bad. 
![Logo](https://cloud.githubusercontent.com/assets/7861426/16390400/e1ebbb50-3ca2-11e6-971c-ad5a13736d99.png)

**Comment by ghost** [comment]
Or use this 

https://www.iconfinder.com/icons/669948/code_coding_html_programming_web_icon#size=128

much cooler and well designed XD

**Comment by ghost** [comment]
Or any of these 

https://www.iconfinder.com/iconsets/web-development-5

**Comment by lluachaturbate** [comment]
I like your own contribution much more than taking something from the internet. Thanks for that, update coming soon.
