### ISSUE TITLE
Show Userlist as Tab

### ISSUE THREAD

**Issue by ghost** [lluachaturbate/CBADK#9]
Is it possible to make a tab control in the chat and have the userlist as a tab? a bit like the original Chaturbate Chat, maybe with a datagrid to edit the fields.

**Comment by lluachaturbate** [comment]
You can edit the fields in the top row already, maybe you missed that?
Anyways if you still think a userlist would be helpful let me know and I'll make something.

**Comment by ghost** [comment]
I know you can do it from the top bar. What i would like to see is something more like the actual site, where you have 2 tabs in the chat area, one with the chat messages and one with the userlist, on the userlist id like something like this, 

![image](https://cloud.githubusercontent.com/assets/7861426/16314391/d46748aa-397d-11e6-9edd-0557628cf80e.png)

**Comment by lluachaturbate** [comment]
Ok, will do something like this as soon as i find the time in the next days.
